### ISSUE TITLE
bad name for cc-add-resource action

### ISSUE THREAD

**Issue by mardaravicius** [Jvinniec/aoe2-aiscript#15]
https://github.com/Jvinniec/aoe2-aiscript/blob/master/languageExtension/src/resources/aoe2Action.json#L137
should be `cc-add-resource`

**Comment by Jvinniec** [comment]
Thanks for catching this! I've implemented your suggested fix into one of the development branches. It will be included in the v0.1.7 release.

**Comment by Jvinniec** [comment]
Fixed and committed to the master branch.
